### ISSUE TITLE
Feature - Implement Fully Linear Interactive Oracle Proofs

### ISSUE THREAD

**Issue by DoHunKim1215** [DoHunKim1215/Simple-FLPCP#1]
# 🔨 Todo

- [x] Parallel Circuit Class
- [x] Function to make interactive proofs and queries
- [ ] (Optional) Implement non-interactive scheme using hash function
